SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
# Spawn asteroids farther outside the screen so they enter smoothly
ASTEROID_SPAWN_MARGIN = ASTEROID_MAX_RADIUS * 4
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3

# Scoring combo constants
BASE_POINTS = 100
COMBO_TIMEOUT_SECONDS = 1.0
COMBO_MAX = 5
